KEYS

Adding empty KEYS file for committers to add KEYS

QUARKS-29 add empty KEYS file

---

samples/topology/src/main/java/quarks/samples/topology/CombiningStreamsProcessingResults.java
samples/utils/src/main/java/quarks/samples/utils/sensor/HeartMonitorSensor.java

Purpose: Applying different processing against a set of streams and combining the resulting streams into a single stream.
- Polls a simulated heart monitor to periodically obtain blood pressure readings.
- Splits the readings by blood pressure category into separate streams.
- Applies different processing on each stream to generate alert streams.
- Combines the alert streams into a single stream and prints the alerts.

[QUARKS-16] [WIP] Add topology sample for combining streams processing results

---

api/topology/src/main/java/quarks/topology/TStream.java
api/topology/src/test/java/quarks/test/topology/TStreamTest.java
console/server/src/main/java/quarks/console/server/ServerUtil.java
samples/topology/src/main/java/quarks/samples/topology/SplitWithEnumSample.java
spi/topology/src/main/java/quarks/topology/spi/graph/ConnectorStream.java

I'm very sorry but there are conflict error on my previous PR.
I tried to solve it but looks hard :( .. So recreate PR
Please refer : #6 Previous Discussion

[QUARKS-18] Split function based upon an enumeration

---

DEVELOPMENT.md

See PR #13 for feedback.
This is in a new PR because PR #13 , while it doesn't yet appear so, was already merged.

Adjust "github use" doc based on feedback.

---

console/servlets/webapp_content/js/index.js
console/servlets/webapp_content/js/metrics.js
samples/console/src/main/java/quarks/samples/console/ConsoleWaterDetector.java

This is for QUARKS-33, when the metrics graph was in between refreshes if the x-axis tick marks were too numerous after changing the metric type selector it appeared with all the numbers mangled.

[QUARKS-33] fixed x-axis legend when many oplets have metrics

---

connectors/pubsub/src/test/java/quarks/test/connectors/pubsub/PubSubTest.java

Test was not waiting for all conditions to become valid.

QUARKS-30 Fix timing issues in PubSubTest

---

NOTICE

Added the IBM Copyright to the NOTICES file for Quarks-34

Add IBM Copyright to NOTICES

---

platform/java7/build.xml

QUARKS-38 Stop java7 testing if java7 jars not built

---

apps/iot/src/main/java/quarks/apps/iot/IotDevicePubSub.java
apps/iot/src/test/java/quarks/test/apps/iot/EchoIotDevice.java
apps/iot/src/test/java/quarks/test/apps/iot/IotDevicePubSubTest.java
build.xml
common-build.xml
connectors/iot/src/main/java/quarks/connectors/iot/Commands.java
connectors/pubsub/src/main/java/quarks/connectors/pubsub/PublishSubscribe.java
providers/iot/.classpath
providers/iot/.project
providers/iot/build.xml
providers/iot/src/main/java/quarks/providers/iot/IotProvider.java
providers/iot/src/main/java/quarks/providers/iot/package-info.java
test/.classpath
test/fvtiot/build.xml
test/fvtiot/src/test/java/quarks/test/fvt/iot/IotAppService.java
test/fvtiot/src/test/java/quarks/test/fvt/iot/IotAppServiceTest.java
test/fvtiot/src/test/java/quarks/test/fvt/iot/IotProviderTest.java
test/fvtiot/src/test/java/quarks/test/fvt/iot/IotTestApps.java

A provider that registers services to allow:
* PublishSubscribe Service
* Application Service
* JSON control service
* use of a single IoTDevice by multiple applications through publish-subsribe
* Integration of device commands with identifier `quarksControl`

[QUARKS-10] Iot provider

---

api/topology/src/test/java/quarks/test/topology/TStreamTest.java
samples/topology/src/main/java/quarks/samples/topology/CombiningStreamsProcessingResults.java
samples/topology/src/main/java/quarks/samples/topology/SplitWithEnumSample.java
samples/utils/src/main/java/quarks/samples/utils/sensor/HeartMonitorSensor.java

note: SplitWithEnumSample imports auto-reorganized by eclipse

[QUARKS-39] cleanup java warnings

---

connectors/mqtt/src/main/java/quarks/connectors/mqtt/iot/MqttDevice.java
samples/apps/src/main/java/quarks/samples/apps/ApplicationUtilities.java
samples/apps/src/main/java/quarks/samples/apps/JsonTuples.java
samples/apps/src/main/java/quarks/samples/apps/sensorAnalytics/Sensor1.java

- remove "batch" window workaround
- improve stream tagging for console use

[QUARKS-54] cleanup SensorAnalytics sample app

---

samples/topology/src/main/java/quarks/samples/topology/CombiningStreamsProcessingResults.java

Change made to avoid using `serialVersionUID`.

[QUARKS-16] Update split to use lambda function

---

samples/.classpath
samples/apps/src/main/java/quarks/samples/apps/ApplicationUtilities.java
samples/apps/src/main/java/quarks/samples/apps/Range.java
samples/apps/src/main/java/quarks/samples/apps/RangeTest.java
samples/apps/src/test/java/quarks/test/samples/apps/RangeTest.java

- clarify wrt Guava Range 
- cleanup Range
- pull test code out into RangeTest
- Note, Range is still just a part of the sample app code.  See QUARKS-78

[QUARKS-79] tidy up Range

---

common-build.xml

I tested in my local and it works
Hmm, And I'm sorry but made lots of sync to apache github repo history..(Merge pull request 2, 3, 4 from apache/master). I tried to remove it, but failed. 
I think it does not affect to logic but please tell me if it cause any nconvenience

[QUARKS-89] Add LICENSE and NOTICE files to jars when building

---

providers/development/src/test/java/quarks/test/providers/dev/DevelopmentProviderTest.java
quarks_overview.html
spi/topology/src/main/java/quarks/topology/spi/graph/TWindowTimeImpl.java

[QUARKS-93] Apply license to quarks_overview.html and adjust static import ordering

---

apps/runtime/src/main/java/quarks/apps/runtime/MonitorApp.java

Addresses comment https://github.com/apache/incubator-quarks/pull/59#discussion-diff-58211233

QUARKS-66: remove MonitorApp extra isolate

---

analytics/sensors/src/main/java/quarks/analytics/sensors/Range.java
analytics/sensors/src/main/java/quarks/analytics/sensors/Ranges.java
analytics/sensors/src/test/java/quarks/test/analytics/sensors/RangeTest.java
samples/.classpath
samples/apps/build.xml
samples/apps/src/main/java/quarks/samples/apps/ApplicationUtilities.java
samples/apps/src/main/java/quarks/samples/apps/package-info.java
samples/apps/src/main/java/quarks/samples/apps/sensorAnalytics/Sensor1.java

- promote samples.apps.Range to quarks.analytics.sensors
- see Range javadoc for Guava Range issues and such

[QUARKS-78] Range analytic utility

---

api/topology/src/main/java/quarks/topology/mbeans/package-info.java
api/topology/src/main/java/quarks/topology/services/ApplicationService.java
apps/iot/src/main/java/quarks/apps/iot/IotDevicePubSub.java
build.xml
connectors/iot/src/main/java/quarks/connectors/iot/Events.java
providers/iot/src/main/java/quarks/providers/iot/IotProvider.java
samples/.classpath
samples/connectors/src/main/java/quarks/samples/connectors/iotf/IotfSensors.java
samples/scenarios/build.xml
samples/scenarios/src/main/java/quarks/samples/scenarios/iotf/IotfFullScenario.java

Sample scenario application demonstrating use of IotProvder and ApplicationService.

Iotf full scenario sample.

---

DEVELOPMENT.md
JAVA_SUPPORT.md
platform/java7/build.xml

Added a couple of jars to Java 7 support to document the process.

Document which Jars run on which Java versions.

---

samples/utils/build.xml
samples/utils/src/main/java/quarks/samples/utils/sensor/SimulatedTemperatureSensor.java

For the motivation / use of this see: https://github.com/apache/incubator-quarks-website/pull/33
Awaiting response to question in the pr.

[QUARKS-107] create SimulatedTemperatureSensor for recipes

---

connectors/wsclient-javax.websocket/src/main/java/quarks/connectors/wsclient/javax/websocket/runtime/WebSocketClientConnector.java

- improve logging to help identify things

[QUARKS-122] [WIP] testReconnectBytes failure on travis

---

samples/utils/src/main/java/quarks/samples/utils/sensor/SimpleSimulatedSensor.java
samples/utils/src/main/java/quarks/samples/utils/sensor/SimulatedTemperatureSensor.java

@queeniema, pls review to ensure this meets your needs/expectations. Thanks.

[QUARKS-129] create SimpleSimulatedSensor

---

NOTICE

Based on advice from mentor Justin McLean, updating the NOTICE file with a simpler IBM copyright statement.

Update NOTICE with shorter IBM copyright

---

console/servlets/webapp_content/js/graph.js
console/servlets/webapp_content/js/index.js
console/servlets/webapp_content/js/metrics.js
samples/scenarios/src/main/java/quarks/samples/scenarios/iotf/IotfFullScenario.java

@ddebrunner Could I ask please review this PR?
(See the previous discussion #81 )

[QUARKS-134] Add missing License header

---

analytics/sensors/src/main/java/quarks/analytics/sensors/Deadtime.java
analytics/sensors/src/main/java/quarks/analytics/sensors/Filters.java

TODO Deadtime fvt, add support of PeriodicMXBean for control

[QUARKS-124] [REVIEW] add Deadtime filter

---

console/server/build.xml
console/servlets/build.xml

adding slf4j log files to the console build.xml files so logging can be added to the console classes

QUARKS-157 console build.xml files

---

connectors/iotf/src/main/java/quarks/connectors/iotf/runtime/IotfDeviceCommands.java
console/servlets/src/main/java/quarks/console/servlets/ConsoleJobServlet.java
console/servlets/src/main/java/quarks/console/servlets/JobUtil.java
console/servlets/src/main/java/quarks/console/servlets/MetricsUtil.java
runtime/appservice/src/main/java/quarks/runtime/appservice/AppServiceControl.java
runtime/etiao/src/main/java/quarks/runtime/etiao/Executable.java
runtime/etiao/src/main/java/quarks/runtime/etiao/Invocation.java
samples/apps/src/main/java/quarks/samples/apps/AbstractApplication.java
samples/console/src/main/java/quarks/samples/console/ConsoleWaterDetector.java
samples/console/src/main/java/quarks/samples/console/HttpServerSample.java

Replaced e.printStackTrace() statements with logger errors.

QUARKS-146 [WIP]

---

api/topology/src/main/java/quarks/topology/plumbing/PlumbingStreams.java
api/topology/src/test/java/quarks/test/topology/PlumbingTest.java

Hmm The sample code in QUARKS-166 looks clearly. I just added test case.
Any advice would be appreciated :)

[QUARKS-166] Add Gate plumbing

---

api/execution/src/main/java/quarks/execution/mbeans/JobMXBean.java
runtime/appservice/src/main/java/quarks/runtime/appservice/AppService.java
runtime/etiao/src/main/java/quarks/runtime/etiao/mbeans/EtiaoJobBean.java
runtime/jsoncontrol/src/main/java/quarks/runtime/jsoncontrol/JsonControlService.java
samples/scenarios/src/main/java/quarks/samples/scenarios/iotf/IotfFullScenario.java

and some tracing for the control & app services

Add the ability to change a job's state from its mbean.

---

providers/direct/src/main/java/quarks/providers/direct/DirectTopology.java
runtime/etiao/src/main/java/quarks/runtime/etiao/EtiaoJob.java
runtime/etiao/src/main/java/quarks/runtime/etiao/Executable.java
runtime/etiao/src/main/java/quarks/runtime/etiao/graph/DirectGraph.java

Fixes JIRA [QUARKS-177](https://issues.apache.org/jira/browse/QUARKS-177).  A Job is created when the topology is submitted,   If a job name is passed in the submit configuration, then that name is used for the Job registration with the ControlService.

Create Job at topology submission time

---

connectors/common/src/test/java/quarks/test/connectors/common/ConnectorTestBase.java
connectors/file/src/test/java/quarks/test/connectors/file/FileStreamsGlobalTest.java
connectors/file/src/test/java/quarks/test/connectors/file/FileStreamsTest.java
connectors/file/src/test/java/quarks/test/connectors/file/FileStreamsTextFileWriterGlobalTest.java
connectors/file/src/test/java/quarks/test/connectors/file/FileStreamsTextFileWriterTest.java
connectors/http/src/test/java/quarks/test/connectors/http/HttpGlobalTest.java
connectors/http/src/test/java/quarks/test/connectors/http/HttpTest.java
connectors/jdbc/src/test/java/quarks/test/connectors/jdbc/JdbcStreamsGlobalTest.java
connectors/jdbc/src/test/java/quarks/test/connectors/jdbc/JdbcStreamsTest.java
connectors/kafka/src/test/java/quarks/test/connectors/kafka/KafkaStreamsGlobalTestManual.java
connectors/kafka/src/test/java/quarks/test/connectors/kafka/KafkaStreamsTestManual.java
connectors/mqtt/src/test/java/quarks/test/connectors/mqtt/MqttStreamsGlobalTestManual.java
connectors/mqtt/src/test/java/quarks/test/connectors/mqtt/MqttStreamsTestManual.java
connectors/pubsub/src/test/java/quarks/test/connectors/pubsub/PubSubGlobalTest.java
connectors/pubsub/src/test/java/quarks/test/connectors/pubsub/PubSubTest.java
connectors/wsclient-javax.websocket/src/test/java/quarks/tests/connectors/wsclient/javax/websocket/WebSocketClientGlobalTest.java
connectors/wsclient-javax.websocket/src/test/java/quarks/tests/connectors/wsclient/javax/websocket/WebSocketClientTest.java

Tests have been added for the following connectors:
* File
* HTTP
* JDBC
* Kafka
* MQTT
* PubSub
* WebSocketClient

[QUARKS-181] Add globalization tests

---

.gitignore
api/build.gradle
api/function/build.gradle
build.gradle
console/servlets/build.gradle
gradle.properties
providers/development/build.gradle
providers/iot/build.gradle
settings.gradle
test/fvtiot/build.gradle

It was modified to Build and Test is run, but is not yet a complete state

Additional work of Gradle Init

---

build.gradle

WIP - All javadoc files are generated but something phrase are different when running diff. I will check it soon

[QUARKS-205] Create gradle Javadoc task

---

api/topology/src/main/java/quarks/topology/mbeans/package-info.java
apps/runtime/src/main/java/quarks/apps/runtime/JobMonitorApp.java
connectors/common/src/main/java/quarks/connectors/runtime/Connector.java
console/server/src/main/java/quarks/console/server/HttpServer.java
providers/iot/src/main/java/quarks/providers/iot/package-info.java
runtime/etiao/src/main/java/quarks/runtime/etiao/EtiaoJob.java
samples/scenarios/src/main/java/quarks/samples/scenarios/iotf/range/sensor/IotfRangeSensor.java
spi/topology/src/main/java/quarks/topology/spi/AbstractTStream.java

I fixed some javadoc statement and remove [wai-aria](https://www.w3.org/WAI/intro/aria.php) in table tag. If this is required or better way exist, please let me know :)

[QUARKS-221] Fix Javadoc syntax

---

console/servlets/webapp_content/html/index.html
console/servlets/webapp_content/js/index.js
console/servlets/webapp_content/resources/css/main.css

Added additional aria-labels and hidden content to enable screen readers to successfully navigate the console.

QUARKS-201 screen reader text

---

api/topology/build.gradle

I found that there are some err occured when gradle build

[QUARKS-223] Junit Parity - 2

---

samples/.classpath

change the classpath to exclude "iotp" (from "iotf")

Fix Eclipse building of iotp sample

---

DEVELOPMENT.md
build.gradle
gradle.properties

- publish groupId is org.apache.edgent
- publish war when applicable

tidy up publishToMavenLocal support

---

console/servlets/webapp_content/js/graph.js
console/servlets/webapp_content/js/index.js

- I looked at the existing defined oplets, updated the current list, and assigned static colors
- For undefined oplets, generate a random color that is perceptually different than all assigned colors. Use a different color scheme for non-org.apache.edgent defined oplets.

[EDGENT-179] Console: Adjust oplet coloring

---

samples/.classpath
samples/scenarios/src/main/java/org/apache/edgent/samples/scenarios/iotp/range/sensor/IotpRangeSensor.java
samples/scenarios/src/main/java/org/apache/edgent/samples/scenarios/iotp/range/sensor/README.md

Edgent-257 cleanup samples/scenarios/iotp

---

build.gradle
edgent_overview.html
platform/java7/build.gradle
platform/java7/build.xml

- download retrolambda to externalJars/java8/tools and use it from there
- unrelated tweak/correction to overview html for location of ext slf4j
jar

Edgent-260 [gradle] remove dependency on retrolambda.jar in repo

---

console/servlets/webapp_content/js/index.js

[EDGENT-200] Console: Tuple count updates

---

DEVELOPMENT.md
KEYS
build.gradle

- update KEYS
- remove KEYS from tgz files
- rename src and binary release images to conform to the norm
- generate sha-512 with extension '.sha'

Edgent-274 Add support for distribution signing

---

.mailmap
CONTRIBUTORS

[WIP] [EDGENT-292] Add mailmap and contributors list

---

buildTools/check_sigs.sh
buildTools/make_release_branch.sh

Add check_sigs.sh
Add make_release_branch.sh

[WIP] Add some release process tools

---

build.gradle

cherry picked from master
also generalize publish handling

Merge pr 229 to release1.0.0

---

api/topology/build.gradle
build.gradle
build.xml
platform/java7/build.xml
providers/direct/src/test/java/org/apache/edgent/test/providers/direct/appservice/AppServiceTest.java
test/fvtiot/src/test/java/org/apache/edgent/test/fvt/iot/IotAppServiceTest.java

Add "incubating" to release bundle names
Exclude KEYS from source bundle
Add CONTRIBUTORS to the binary bundle
Remove test.classes/*.APPS.TEST.jar from source bundle
Build *.APPS.TEST.jar under gradle "build" tree
Add cleanup of old ant build artifacts to cleanAll
Cleanup intermediate classes.{in,out} created by retro7 processing

Build fixes

---

buildTools/download_edgent_asf.sh
samples/topology/src/main/java/org/apache/edgent/samples/topology/SensorsAggregates.java

- download_edgent_asf.sh: echo check_sig cmds
- SensorAggregates sample: report Console url

misc minor tweaks

---

providers/iot/src/main/java/org/apache/edgent/providers/iot/IotProvider.java

[Edgent-367] Add autoSubmit to IotProvider

---

connectors/.classpath
connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/IotpDevice.java
connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/runtime/IotpConnector.java
samples/.classpath
samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpQuickstart2.java
scripts/connectors/iotp/runiotpquickstart2.sh

- add IotpDevice(DeviceClient) ctor
- add quickstart sample that uses it

[Edgent-376] Support use in WIoTP Managed Device context

---

buildTools/stage_release_candidate.sh

- stage the correct file to binaries/LICENSE
- handle svn case of add of initial staged edgent-<ver> dir
- fix the svn commit cmd's msg quoting

[Edgent-385] fix stage_release_candidate.sh

---

connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/IotpGateway.java
edgent_overview.html
samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpAppClient.java
samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpDeviceSample.java
samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpGWDeviceSample.java
samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpQuickstart.java
samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpQuickstart2.java
samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpSensors.java
samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/package-info.java

- update the overview javadoc samples table
- update the sample/connector/iotp package doc
- update the sample's doc

[Edgent-387] update iotp sample javadoc

---

apps/runtime/src/main/java/org/apache/edgent/apps/runtime/JobMonitorApp.java
apps/runtime/src/test/java/org/apache/edgent/test/apps/runtime/JobMonitorAppTest.java

- instrument/validate JobMonitorAppTest
- fix JobMonitorApp event filtering

[Edgent-396] JobMonitorApp restarts job 3x more than it should

---

providers/iot/src/main/java/org/apache/edgent/providers/iot/IotProvider.java
providers/iot/src/main/java/org/apache/edgent/providers/iot/package-info.java

- rework to make use of IotProvider clearer
- reduce prominence of how it does what it does
- added clarification for use of registerJar

[Edgent-405] improve IotProvider doc wrt registerJar

---

api/topology/src/main/java/org/apache/edgent/topology/json/JsonFunctions.java
api/topology/src/test/java/org/apache/edgent/test/topology/JsonFunctionsTest.java
connectors/mqtt/src/test/java/org/apache/edgent/test/connectors/mqtt/MqttOpenTest.java

add valueOf*()
add unpartitioned()
cleanup some earlier javadoc

[Edgent-407] JsonFunctions additions

---

DEVELOPMENT.md
README.md

- also tweaks to better work with Eclipse's Markdown text Editor's view.

[Edgent-421] link to wiki from Development.md

---

platforms/android/android/hardware/pom.xml
platforms/android/android/topology/pom.xml
platforms/android/pom.xml
platforms/java7/pom.xml

started getting import issues.  maybe had residual settings covering for
me previously.
- add missing m2e "ignore" in platforms/java7/pom.xml
- add the same to platforms/android/pom.xml and remove it from the
children android/{hardware,topology}/pom.xml

fix eclipse import problems

---

JAVA_SUPPORT.md

fix `<ver>` portion of jar name not getting rendered

Fix JAVA_SUPPORT.md markdown

---

buildTools/download_edgent_asf.sh

LICENSE no longer a separate staged file in the dev/release repo

update download script for LICENSE removal
