apache/incubator-edgent

api/execution/src/main/java/quarks/execution/Job.java, api/execution/src/main/java/quarks/execution/mbeans/JobMXBean.java, providers/direct/src/test/java/quarks/test/providers/direct/DirectJobTest.java, runtime/etiao/src/main/java/quarks/runtime/etiao/EtiaoJob.java, runtime/etiao/src/main/java/quarks/runtime/etiao/Executable.java, runtime/etiao/src/main/java/quarks/runtime/etiao/mbeans/EtiaoJobBean.java, samples/topology/src/main/java/quarks/samples/topology/DevelopmentSampleJobMXBean.java, samples/topology/src/main/java/quarks/samples/topology/JobEventsSample.java, spi/graph/src/main/java/quarks/graph/spi/execution/AbstractGraphJob.java
Contains updates to the Job interface and runtime implementation:
- Job.Health enum: HEALTHY, UNHEALTHY 
- Job.getHealth() - current health value
- Job.getLastError() - message of the exception which caused the job to become unhealthy
=> QUARKS-12 [WIP] Provide job health info

build.xml, quarks_overview.html
Include incubation disclaimer in the Javadoc overview as the incubator branding indicates documentation must have the disclaimer.
http://incubator.apache.org/guides/branding.html
=> Change IBM copyrights to required ASF branding for Javadoc

samples/topology/src/main/java/quarks/samples/topology/TerminateAfterNTuples.java, scripts/cron/README, scripts/cron/startapp.cron, scripts/cron/startapp.sh
Simple mechanism to restart a Quarks application if the JVM running Quarks terminates unexpectedly:
- Sample application which simulates a JVM crash after processing N tuples
- Script which checks whether the Quarks JVM is still running, otherwise it restarts the Quarks sample app
- Cron entry which runs the script every mnute
- Readme providing setup instructions
=> QUARKS-13: Start over Quarks when the JVM crashes (Linux)

console/servlets/webapp_content/js/ext/d3.legend.js, console/servlets/webapp_content/js/graph.js, console/servlets/webapp_content/js/index.js
Currently the code that colors the stream tags and the legend for the stream tags uses a default color range called color20, part of the d3 library.  One of the colors in that range is a light grey that looks like the links that do not have stream tags.  I replaced that color with a teal color in the graph and the legend
=> QUARKS-53 changed light grey tag color

DEVELOPMENT.md
Ref : [https://github.com/apache/incubator-quarks-website/pull/29](https://github.com/apache/incubator-quarks-website/pull/29)
=> [QUARKS-101] GitHub references should be GitHub not Github

api/topology/src/main/java/quarks/topology/plumbing/PlumbingStreams.java, api/topology/src/test/java/quarks/test/topology/PlumbingTest.java
- Add PlumbingStreams.parallel()
- Add PlumbingStreams.parallelMap()
- Add PlumbingStreams.roundRobinSplitter()
These are in contrast to the new concurrent[Map]() in PR-99.
=> [QUARKS-165] add traditional parallel analytics

api/topology/src/main/java/quarks/topology/plumbing/LoadBalancedSplitter.java, api/topology/src/main/java/quarks/topology/plumbing/PlumbingStreams.java, api/topology/src/test/java/quarks/test/topology/PlumbingTest.java
- Add PlumbingStreams.parallelBalanced()
- Add LoadBalancedSplitter ToIntFunction
- Add testParallelBalanced()
Note: there's an oplet based implementation approach to a LoadBalancedSplitter that doesn't require "done" signaling nor separate ch "isolate()" use - one that has an internal thread pool pulling from single tuple queue.  Utilizing such a 1:n (~fanout) oplet would require adding something like ``TStream.split(Split)`` or perhaps ``TStream.addOp1N(oplet-with-one-input-and-N-output)``.
I'm sure there's a similar *functional* LoadBalancedSplitter possible and maybe I'll give that a little thought shortly.  Though, at this moment there's no way for Functions to get their hands on the Provider's thread pool nor receive explicit initialization.
=> [QUARKS-173] add load balanced parallel()

analytics/sensors/src/test/java/quarks/test/analytics/sensors/FiltersTest.java
got a couple of failures where 1,4,6,10 was received instead of 1,4,6,9.
Think the deadtime change was a bit too long so 9 wasn't outside of the
time-band.
=> [QUARKS-197] tweak test's timing for intermittent failures

api/graph/src/main/java/quarks/graph/Connector.java, api/graph/src/main/java/quarks/graph/Graph.java, api/topology/src/test/java/quarks/test/topology/TStreamTest.java, providers/development/src/main/java/quarks/providers/development/DevelopmentProvider.java, runtime/etiao/src/main/java/quarks/runtime/etiao/Invocation.java, runtime/etiao/src/main/java/quarks/runtime/etiao/graph/EtiaoConnector.java, runtime/etiao/src/main/java/quarks/runtime/etiao/graph/ExecutableVertex.java, runtime/etiao/src/main/java/quarks/runtime/etiao/graph/Target.java, spi/graph/src/main/java/quarks/graph/spi/AbstractGraph.java, spi/graph/src/main/java/quarks/graph/spi/DirectEdge.java, utils/metrics/src/main/java/quarks/metrics/Metrics.java, utils/streamscope/src/main/java/quarks/streamscope/StreamScopeSetup.java
- fix the case
- this is an incremental ~minimal change fix. It feels a bit hacky and
doesn't address some other concerns with the EtiaoConnector.
- enhance tests to include the case
- clarify Connector.isConnect()'s existing semantics
=> [QUARKS-120] fix broken graph for "middle peek fanout" case

api/window/src/test/java/quarks/test/window/WindowTest.java
Operations on unsynchronized lists used concurrently can fail intermittently. Tests adjusted to prevent such failures.
=> synchronized lists used in concurrent code in tests

.gitignore
I mainly use the IntelliJ Idea, so I think it will be helpful if gitignore including an IntelliJ file extensions.
=> Add IntelliJ Idea file extension to gitignore

console/servlets/webapp_content/html/index.html, console/servlets/webapp_content/js/index.js, console/servlets/webapp_content/resources/css/main.css
Added tab indices to a lot of the html on the page and keypress handlers for some of the controls.
Now the user can tab to open the hover for the job state and also tab (then push enter) to see all the properties in the graph.  Using the browser specific keys to close a popup/window will close the window containing the table.
i.e, On MAC it is command + W
=> QUARKS-201 added keyboard support to console

api/topology/build.gradle, build.gradle, console/server/src/main/java/org/apache/edgent/console/server/ServerUtil.java, console/servlets/build.gradle, providers/direct/build.gradle
- I'm working on but little more testing needed
- I did not want to call the ant.jar in gradle but was unable to add the file to the META-INF/service. Please teach me if anyone has a good idea.
- I modified ServerUtil.java to avoid error when there are 2 or more console.war(in webapp directory) but does not looks good. I think this remainning in a temporarily until @dlaboss 's work
=> [QUARKS-223] Junit parity

api/execution/src/main/java/org/apache/edgent/execution/services/RuntimeServices.java, build.gradle, connectors/command/src/main/java/org/apache/edgent/connectors/command/runtime/CommandReader.java
- Explicitly pickup doc-files files to fix topology/package-info:"Edgent
Source Streams" link and analytics/sensors/Filters:"Deadband example"
link
- cleanup two javadoc warnings/errors
=> Quarks-205 fix gradle broken javadoc doc-files links

build.gradle, edgent_overview.html, utils/streamscope/src/main/java/org/apache/edgent/streamscope/oplets/package-info.java
- fix for iotf to iotp rename
- tweak directions for building applications for new iot provider and
new connectors
- tweak overview doc now that "join" exists
- reorder overview's javadoc categories
- eliminate connectors/**/runtime, and some others, from generated
javadoc (parity with ant builds)
=> Quarks-205 fix gradle generated overview javadoc

DEVELOPMENT.md, build.gradle, settings.gradle
- add defaultTask "all"
- add "release" with tgz generation (depends on "all")
- add "all" assemble and populate target_dir with jars, javadoc, etc
- remove "build" dependsOn aggregateJavadoc, copyJar
- remove "aggregateJavadoc" dependsOn/runs tests
- remove "jacocoTestReport" dependsOn copyJar
with this commit, tgz is still missing:
- samples source
- oplet/core/mbeans javadoc
- svt jar
- console war
- jars from project ext dirs and top-level ext jars
=> Quarks-205 add gradle "release" and "all" task

build.gradle
WIth the updated build.gradle, one can publish edgent to local maven repository via:
gradle publishToMavenLocal
This is especially useful when edgent is used with another Maven/Gradle project.
=> Enable Edgent to publish to maven repository

console/servlets/webapp_content/html/index.html, console/servlets/webapp_content/js/ext/d3.legend.js, console/servlets/webapp_content/js/index.js
Added some extra space around the legend box in the console due to the longer package names after changing from apache.quarks to org.apache.edgent.
=> EDGENT_243 console legend wider

android/hardware/src/main/java/org/apache/edgent/android/hardware/SensorStreams.java, android/hardware/src/main/java/org/apache/edgent/android/hardware/runtime/SensorChangeEvents.java, android/hardware/src/main/java/org/apache/edgent/android/hardware/runtime/SensorSourceSetup.java, android/topology/build.xml, android/topology/src/main/java/org/apache/edgent/android/oplet/RunOnUIThread.java, android/topology/src/main/java/org/apache/edgent/android/topology/ActivityStreams.java
- fix bug in android/topology/build.xml -- missing oplet jar presumably
from earlier refactoring
- fix bugs in android/{hardware,topology} classes -- import names from
quarks->edgent rename.
Need to "ant release" with ANDROID_SDK_PLATFORM ev set to see thebuild
problems in the absence of these changes.
=> Edgent-247 fix android/{hardware,topology} ant build

LICENSE, console/servlets/LICENSE, console/servlets/webapp_content/js/ext/MIT.LICENSE, console/servlets/webapp_content/js/ext/jquery-ui-1.11.4.custom/jquery-ui.LICENSE
I added a console/servlets/LICENSE file containing the following:
This initial line of text:
"This product contains content covered by MIT/BSD-3-Clause licenses."
then where the ext files came from, and their associated license type, a URL to the license or path in the repository to the license, and added a couple of license.
I also updated <repo>/LICENSE to mention the console/servlets/LICENSE file
=> EDGENT-262 console license changes

DEVELOPMENT.md
Apache Infra said "older archives will remain the old name" in [INFRA-12281](https://issues.apache.org/jira/browse/INFRA-12281)
So previous mailing archive addresses should point to Quarks.
=> Changes to the previous version of the archive address

DEVELOPMENT.md, build.gradle, edgent_overview.html, gradle.properties, legal/source-release-readme
add "apache" to tgz names
add SNAPSHOT and <DATE>-<TIME> to build tgz name when appropriate
make src tgz extract to different dir than binary tgz
update current snapshot build version id
fix URL in source release README
remove version Id in edgent_overview.html (additional maintenance and
it's already present on the javadoc page that the overview is
incorporated into).
=> Edgent-281 Misc build changes for "release"

DEVELOPMENT.md, android/hardware/build.gradle, android/hardware/build.xml, android/topology/build.gradle, android/topology/build.xml, build.gradle, platform/java7/build.gradle, platform/java7/build.xml, settings.gradle
Get android.jar from maven for compilation
Note: the android jar is not included in the binary tgz.
ANDROID_SDK_PLATFORM is no longer used / has no effect.
=> Edgent-304 Always build edgent.android.{hardware,topology}.jar

build.gradle
This commit fixed the following issue:
In the current version, if you run gradle publishToMavenLocal or gradle publish, it will throw the following error:
Execution failed for task ':platform:android:publishMavenJavaPublicationToMavenLocal'.
> Failed to publish publication 'mavenJava' to repository 'mavenLocal'
> Invalid publication 'mavenJava': artifact file does not exist: '/git/quarks/incubator-edgent/build/distributions/java8/platform/android/lib/edgent.platform.android.jar'
The edgent.platform.java project also has the similar problem that prevent the project from publishing to Maven.
=> Fix publish by ignoring platform projects

LICENSE, binary-release/LICENSE, licenses/sizzle.MIT
bundled jquery-ui bundles jquery which bundles sizzle (see our bundled
jquery.js)
update jquery.MIT license with license text from jquery-1.10.2 in github
(version noted in jquery.js)
add licenses/sizzle.MIT for sizzle version bundled by jquery-1.10.2
(jquery-1.10.2 github links to sizzle 1.10.2 github version)
=> add Sizzle license

runtime/etiao/src/main/java/org/apache/edgent/runtime/etiao/EtiaoJob.java
=> Set auto-assigned Job name at construction time instead of in getName()

connectors/mqtt/src/main/java/org/apache/edgent/connectors/mqtt/MqttConfig.java
Had a space at the end of the property and it was unclear why the URL
failed validation.
=> [Edgent-366] Tolerate trailing spaces in serverURLs MqttConfig properties file

scripts/connectors/iotp/runiotpsensors.sh
- remove the sample run script workaround that was added earlier
=> [Edgent-380] update MQTT connector to use paho-mqtt 1.1.0

RELEASE_NOTES, apps/iot/src/main/java/org/apache/edgent/apps/iot/PubSubIotDevice.java, apps/iot/src/test/java/org/apache/edgent/test/apps/iot/EchoIotDevice.java, build.gradle, connectors/iot/src/main/java/org/apache/edgent/connectors/iot/IotDevice.java, connectors/iot/src/main/java/org/apache/edgent/connectors/iot/IotGateway.java, connectors/iot/src/main/java/org/apache/edgent/connectors/iot/package-info.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/IotpDevice.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/IotpGWDevice.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/IotpGateway.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/runtime/IotpConnector.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/runtime/IotpGWCommands.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/runtime/IotpGWConnector.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/runtime/IotpGWDeviceEventsFixed.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/runtime/IotpGWDeviceEventsFunction.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/runtime/IotpGWEventsFixed.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/runtime/IotpGWEventsFunction.java, connectors/mqtt/src/main/java/org/apache/edgent/connectors/mqtt/iot/MqttDevice.java, samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpAppClient.java, samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpDeviceSample.java, samples/connectors/src/main/java/org/apache/edgent/samples/connectors/iotp/IotpGWDeviceSample.java, scripts/connectors/iotp/README, scripts/connectors/iotp/iotp-app-client.cfg, scripts/connectors/iotp/iotp-device-sample.cfg, scripts/connectors/iotp/iotp-gwdevice-sample.cfg, scripts/connectors/iotp/run-iotp-app-client.sh, scripts/connectors/iotp/run-iotp-device-sample.sh, scripts/connectors/iotp/run-iotp-gwdevice-sample.sh
Add IotGateway
Add IotDevice.{getDeviceType(),getDeviceId(),CMD_DEVICE}
These IotDevice changes break existing IotDevice implementations but in
practice this won't be a problem - its highly unlikely any IotDevice
implementations exist outside of this repository (and adapting is
trivial).  "default" can't be used due to support for Java7/Android.  
Other schemes are possible that avoid this but they don't model things
as well (an IotDevice really does have an Id), introduce even more types
(e.g., a IotGatewayConnectedDevice), and/or are less convenient to use.
e.g., those new IotDevice methods could be migrated to IotGateway -
IotGateway.getDeviceId(IotDevice).
=> [Edgent-377] IotGateway

analytics/math3/src/main/java/org/apache/edgent/analytics/math3/Aggregations.java, analytics/math3/src/main/java/org/apache/edgent/analytics/math3/json/JsonAnalytics.java, api/execution/src/main/java/org/apache/edgent/execution/mbeans/PeriodMXBean.java, api/execution/src/main/java/org/apache/edgent/execution/services/ControlService.java, api/topology/src/main/java/org/apache/edgent/topology/TWindow.java, api/topology/src/main/java/org/apache/edgent/topology/json/JsonFunctions.java, api/topology/src/main/java/org/apache/edgent/topology/mbeans/package-info.java, api/topology/src/main/java/org/apache/edgent/topology/plumbing/PlumbingStreams.java, connectors/command/src/main/java/org/apache/edgent/connectors/command/runtime/ProcessReader.java, connectors/iot/src/main/java/org/apache/edgent/connectors/iot/Commands.java, connectors/iotp/src/main/java/org/apache/edgent/connectors/iotp/IotpDevice.java, connectors/mqtt/src/test/java/org/apache/edgent/test/connectors/mqtt/MqttOpenTest.java, providers/iot/src/main/java/org/apache/edgent/providers/iot/IotProvider.java, utils/streamscope/src/main/java/org/apache/edgent/streamscope/StreamScope.java, utils/streamscope/src/main/java/org/apache/edgent/streamscope/StreamScopeRegistry.java, utils/streamscope/src/main/java/org/apache/edgent/streamscope/mbeans/StreamScopeRegistryMXBean.java
Seen when failOnError is enabled
- remove cross project links to non-dependent projects
- remove anchor refs from @see
- replace problem '>' with &gt;
- remove problem </P>
=> [Edgent-424] Cleanup things maven-javadoc-plugin 2.10.4 complains about

utils/metrics/src/main/java/org/apache/edgent/metrics/MetricsSetup.java
In the current project status only had the support will JMX. So it was implementing the support to generate ._csv_ files in accordance with [metrics library](http://metrics.dropwizard.io/3.1.0/manual/core/#man-core-reporters-csv) already used in the project.
[[EDGENT-428] Adding support for csv in MetricsSetup](https://issues.apache.org/jira/browse/EDGENT-428)
=> [EDGENT-428] Adding support for csv in MetricsSetup

buildTools/check_jar.sh, buildTools/check_jars.sh, buildTools/release_jars_android.txt, buildTools/release_jars_std.txt
Initial version of tools to help check that a release contains the
appropriate jars and they have the required metadata content.
This version lacks integration with Nexus - the real target of this
validation checking.  If there's a tool that can download all of the
jars present in a nexus staging area then this tool can be run against
that downloaded tree.
=> add release validation check_jars.sh
